directories:
  output: release
  buildResources: build
appId: com.prestige-ai.app
productName: Prestige-AI
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
extraResources:
  - from: assets/
    to: assets/
    filter:
      - '**/*'
publish:
  provider: github
  owner: United-Visions
  repo: Prestige-Ai
mac:
  category: public.app-category.developer-tools
  target:
    - target: dmg
      arch:
        - x64
        - arm64
    - target: zip
      arch:
        - x64
        - arm64
  icon: assets/icon/icon.icns
  hardenedRuntime: true
  gatekeeperAssess: false
  entitlements: build/entitlements.mac.plist
  entitlementsInherit: build/entitlements.mac.plist
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
    - target: zip
      arch:
        - x64
        - ia32
  icon: assets/icon/icon.ico
linux:
  target:
    - target: AppImage
      arch:
        - x64
    - target: tar.gz
      arch:
        - x64
  icon: assets/icon/icon.png
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
dmg:
  contents:
    - x: 110
      'y': 150
    - x: 240
      'y': 150
      type: link
      path: /Applications
electronVersion: 27.3.11
